-- ExtraWork core schema.
-- Report §9.3 (core schema) and §9.4 (indexing plan).
--
-- Conventions:
--   * every tenant-owned table carries organization_id and every tenant query
--     starts with it (report §9.4);
--   * money is bigint minor units, never numeric/float (report §8.1, §14.4);
--   * identifiers are UUIDv7, generated by the application for index locality
--     (report §7.2);
--   * mutable tables carry lock_version for optimistic locking (report §7.8).

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

CREATE TYPE membership_role AS ENUM
  ('OWNER','ADMIN','PROJECT_MANAGER','FINANCE','VIEWER');

CREATE TYPE project_status AS ENUM
  ('ACTIVE','ON_HOLD','CLOSED','ARCHIVED','INTEGRITY_REVIEW');

CREATE TYPE change_type AS ENUM
  ('ADDITION','DEDUCTION','SUBSTITUTION','TIME_ONLY');

CREATE TYPE version_status AS ENUM
  ('DRAFT','SENT','VIEWED','REVISION_REQUESTED','APPROVED','DECLINED',
   'EXPIRED','CANCELLED','SUPERSEDED');

CREATE TYPE decision_type AS ENUM ('APPROVE','DECLINE','REQUEST_REVISION');

CREATE TYPE assurance_level AS ENUM ('A0','A1','A2');

CREATE TYPE actor_type AS ENUM ('USER','CUSTOMER','SYSTEM','SUPPORT','PROVIDER');

CREATE TYPE scan_status AS ENUM ('PENDING','SCANNING','CLEAN','REJECTED','FAILED');

CREATE TYPE job_status AS ENUM ('PENDING','RUNNING','COMPLETED','FAILED','DEAD_LETTER');

-- ---------------------------------------------------------------------------
-- Organizations, users, memberships
-- ---------------------------------------------------------------------------

CREATE TABLE organizations (
  id uuid PRIMARY KEY,
  display_name text NOT NULL,
  legal_name text,
  gstin text,
  timezone text NOT NULL DEFAULT 'Asia/Kolkata',
  default_currency char(3) NOT NULL DEFAULT 'INR',
  retention_months integer NOT NULL DEFAULT 36
    CHECK (retention_months BETWEEN 1 AND 120),
  status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
  brand_primary_color text,
  contact_phone text,
  contact_email text,
  -- Reminder policy steps in hours after send (report §8.6).
  reminder_policy_hours integer[] NOT NULL DEFAULT ARRAY[24, 72],
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lock_version integer NOT NULL DEFAULT 1
);

CREATE TABLE users (
  id uuid PRIMARY KEY,
  -- Only the provider subject is stored; the managed provider owns credentials
  -- (report §6.5).
  auth_provider text NOT NULL DEFAULT 'local',
  auth_provider_subject text NOT NULL UNIQUE,
  email_normalized text NOT NULL,
  display_name text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','SUSPENDED','DELETED')),
  last_authenticated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_idx ON users (email_normalized);

CREATE TABLE memberships (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role membership_role NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE','INVITED','REVOKED')),
  invited_by_user_id uuid REFERENCES users(id),
  invitation_token_hash bytea,
  invitation_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, user_id)
);

CREATE INDEX memberships_user_idx ON memberships (user_id, status);
-- Exactly one active owner per organization.
CREATE UNIQUE INDEX memberships_single_owner_idx
  ON memberships (organization_id)
  WHERE role = 'OWNER' AND status = 'ACTIVE';

-- Business sessions. Report §6.5: cookie holds an opaque id, never a bearer JWT.
CREATE TABLE sessions (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL UNIQUE,
  active_organization_id uuid REFERENCES organizations(id) ON DELETE SET NULL,
  csrf_token_hash bytea NOT NULL,
  authenticated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  ip_hash bytea,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_idx ON sessions (user_id) WHERE revoked_at IS NULL;
CREATE INDEX sessions_expiry_idx ON sessions (expires_at) WHERE revoked_at IS NULL;

-- Magic links for the first-party auth driver.
CREATE TABLE auth_challenges (
  id uuid PRIMARY KEY,
  email_normalized text NOT NULL,
  token_hash bytea NOT NULL UNIQUE,
  purpose text NOT NULL CHECK (purpose IN ('SIGN_IN','INVITATION')),
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  attempt_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX auth_challenges_email_idx ON auth_challenges (email_normalized, created_at DESC);

-- ---------------------------------------------------------------------------
-- Customers and contacts
-- ---------------------------------------------------------------------------

CREATE TABLE customers (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  display_name text NOT NULL,
  legal_name text,
  notes text,
  -- Unaccented, lowercased search text kept separate from the display value
  -- (report §9.5).
  search_document tsvector,
  merged_into_customer_id uuid REFERENCES customers(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lock_version integer NOT NULL DEFAULT 1
);

CREATE INDEX customers_org_idx ON customers (organization_id, updated_at DESC);
CREATE INDEX customers_search_idx ON customers USING gin (search_document);
CREATE INDEX customers_name_trgm_idx ON customers USING gin (display_name gin_trgm_ops);
CREATE INDEX customers_merged_idx ON customers (merged_into_customer_id)
  WHERE merged_into_customer_id IS NOT NULL;

CREATE TABLE contacts (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone_e164 text,
  email_normalized text,
  is_default_approver boolean NOT NULL DEFAULT false,
  authority_note text,
  whatsapp_opt_in_status text NOT NULL DEFAULT 'UNKNOWN'
    CHECK (whatsapp_opt_in_status IN ('UNKNOWN','OPTED_IN','OPTED_OUT')),
  whatsapp_opt_in_at timestamptz,
  whatsapp_opt_in_source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (phone_e164 IS NOT NULL OR email_normalized IS NOT NULL),
  CHECK (phone_e164 IS NULL OR phone_e164 ~ '^\+[1-9][0-9]{7,14}$')
);

CREATE INDEX contacts_customer_idx ON contacts (organization_id, customer_id);
CREATE INDEX contacts_org_phone_idx ON contacts (organization_id, phone_e164);
CREATE INDEX contacts_org_email_idx ON contacts (organization_id, email_normalized);
CREATE UNIQUE INDEX contacts_default_approver_idx
  ON contacts (customer_id) WHERE is_default_approver;

-- ---------------------------------------------------------------------------
-- Projects and baselines
-- ---------------------------------------------------------------------------

CREATE TABLE projects (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  project_number text NOT NULL,
  title text NOT NULL,
  site_address_json jsonb,
  status project_status NOT NULL DEFAULT 'ACTIVE',
  currency char(3) NOT NULL,
  timezone text NOT NULL,
  baseline_subtotal_minor bigint NOT NULL,
  baseline_tax_minor bigint NOT NULL,
  baseline_total_minor bigint NOT NULL,
  -- Materialized projection, rebuilt by the integrity job (report §13.3).
  approved_delta_minor bigint NOT NULL DEFAULT 0,
  revised_total_minor bigint NOT NULL,
  approved_schedule_delta_days integer NOT NULL DEFAULT 0,
  start_date date,
  expected_completion_date date,
  default_approver_contact_id uuid REFERENCES contacts(id),
  baseline_document_file_id uuid,
  -- Latches true on first send; drives the baseline lock (report §4.1, §4.6).
  has_sent_change boolean NOT NULL DEFAULT false,
  search_document tsvector,
  retention_until date,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lock_version integer NOT NULL DEFAULT 1,
  UNIQUE (organization_id, project_number),
  CHECK (baseline_subtotal_minor >= 0 AND baseline_tax_minor >= 0),
  CHECK (baseline_total_minor = baseline_subtotal_minor + baseline_tax_minor),
  CHECK (revised_total_minor = baseline_total_minor + approved_delta_minor),
  -- Report §4.6: the revised total can never go negative.
  CHECK (revised_total_minor >= 0)
);

CREATE INDEX projects_org_status_idx
  ON projects (organization_id, status, updated_at DESC);
CREATE INDEX projects_customer_idx ON projects (organization_id, customer_id);
CREATE INDEX projects_search_idx ON projects USING gin (search_document);
CREATE INDEX projects_title_trgm_idx ON projects USING gin (title gin_trgm_ops);

-- Baseline history. The first row is the original; later rows are explicit,
-- audited amendments (report §4.1).
CREATE TABLE baseline_versions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version_number integer NOT NULL CHECK (version_number > 0),
  subtotal_minor bigint NOT NULL,
  tax_minor bigint NOT NULL,
  total_minor bigint NOT NULL,
  reason text,
  effective_date date,
  supporting_file_id uuid,
  recorded_by_user_id uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, version_number),
  CHECK (total_minor = subtotal_minor + tax_minor)
);

CREATE TABLE project_members (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id)
);

CREATE INDEX project_members_user_idx ON project_members (user_id, organization_id);

-- ---------------------------------------------------------------------------
-- Files
-- ---------------------------------------------------------------------------

CREATE TABLE file_objects (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  storage_key text NOT NULL UNIQUE,
  -- Set once the object is promoted out of quarantine (report §9.7).
  promoted_storage_key text UNIQUE,
  original_filename text NOT NULL,
  declared_mime_type text,
  detected_mime_type text,
  byte_size bigint NOT NULL CHECK (byte_size >= 0),
  sha256 bytea,
  scan_status scan_status NOT NULL DEFAULT 'PENDING',
  scan_detail text,
  scanned_at timestamptz,
  storage_version text,
  purpose text NOT NULL DEFAULT 'CHANGE_ATTACHMENT',
  image_width integer,
  image_height integer,
  -- Sanitised, EXIF-stripped derivative shown to customers (report §9.7).
  derivative_storage_key text,
  uploaded_by_user_id uuid REFERENCES users(id),
  uploaded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX file_objects_org_idx ON file_objects (organization_id, created_at DESC);
CREATE INDEX file_objects_scan_idx ON file_objects (scan_status)
  WHERE scan_status IN ('PENDING','SCANNING');
-- Byte-level dedupe within an organization, only after a clean scan (§9.5).
CREATE INDEX file_objects_sha_idx ON file_objects (organization_id, sha256)
  WHERE sha256 IS NOT NULL AND scan_status = 'CLEAN';

ALTER TABLE projects
  ADD CONSTRAINT projects_baseline_document_fk
  FOREIGN KEY (baseline_document_file_id) REFERENCES file_objects(id);

ALTER TABLE baseline_versions
  ADD CONSTRAINT baseline_versions_file_fk
  FOREIGN KEY (supporting_file_id) REFERENCES file_objects(id);

-- ---------------------------------------------------------------------------
-- Change orders and versions
-- ---------------------------------------------------------------------------

CREATE TABLE change_orders (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  number text NOT NULL,
  type change_type NOT NULL,
  current_version_id uuid,
  created_by_user_id uuid NOT NULL REFERENCES users(id),
  -- A correction to an approved change is a new linked change (report §4.3).
  reversal_of_change_order_id uuid REFERENCES change_orders(id),
  search_document tsvector,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (project_id, number)
);

CREATE INDEX changes_project_created_idx
  ON change_orders (organization_id, project_id, created_at DESC);
CREATE INDEX changes_search_idx ON change_orders USING gin (search_document);

CREATE TABLE change_order_versions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  change_order_id uuid NOT NULL REFERENCES change_orders(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  version_number integer NOT NULL CHECK (version_number > 0),
  status version_status NOT NULL DEFAULT 'DRAFT',
  type change_type NOT NULL,
  title text NOT NULL,
  scope_description text NOT NULL,
  reason text,
  schedule_delta_days integer NOT NULL DEFAULT 0,
  revised_completion_date date,
  approver_contact_id uuid NOT NULL REFERENCES contacts(id),
  assurance_required assurance_level NOT NULL DEFAULT 'A0',
  currency char(3) NOT NULL,
  subtotal_delta_minor bigint NOT NULL DEFAULT 0,
  tax_delta_minor bigint NOT NULL DEFAULT 0,
  total_delta_minor bigint NOT NULL DEFAULT 0,
  -- Frozen at send: the baseline and prior-approved figures as they stood.
  baseline_total_minor bigint,
  prior_approved_delta_minor bigint,
  revised_contract_total_minor bigint,
  canonical_snapshot jsonb,
  canonical_sha256 bytea,
  canonicalizer_version text,
  terms_version text,
  sent_at timestamptz,
  viewed_at timestamptz,
  decided_at timestamptz,
  expires_at timestamptz,
  superseded_by_version_id uuid,
  created_by_user_id uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  lock_version integer NOT NULL DEFAULT 1,
  UNIQUE (change_order_id, version_number),
  CHECK (total_delta_minor = subtotal_delta_minor + tax_delta_minor),
  -- A draft has no snapshot; anything sent or later always has one (report §9.3).
  CHECK (
    (status = 'DRAFT' AND canonical_snapshot IS NULL) OR
    (status <> 'DRAFT' AND canonical_snapshot IS NOT NULL)
  ),
  CHECK (status = 'DRAFT' OR sent_at IS NOT NULL),
  CHECK (status = 'DRAFT' OR expires_at IS NOT NULL)
);

ALTER TABLE change_orders
  ADD CONSTRAINT fk_current_version
  FOREIGN KEY (current_version_id) REFERENCES change_order_versions(id)
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE change_order_versions
  ADD CONSTRAINT fk_superseded_by
  FOREIGN KEY (superseded_by_version_id) REFERENCES change_order_versions(id)
  DEFERRABLE INITIALLY DEFERRED;

-- Report §9.4: pending-request scan for the expiry and reminder jobs.
CREATE INDEX versions_pending_idx
  ON change_order_versions (organization_id, expires_at)
  WHERE status IN ('SENT','VIEWED');
CREATE INDEX versions_change_order_idx
  ON change_order_versions (change_order_id, version_number DESC);
CREATE INDEX versions_project_status_idx
  ON change_order_versions (organization_id, project_id, status);
-- Drives the approved-delta projection rebuild (report §13.3).
CREATE INDEX versions_approved_idx
  ON change_order_versions (project_id)
  WHERE status = 'APPROVED';
CREATE INDEX versions_org_decided_idx
  ON change_order_versions (organization_id, decided_at DESC)
  WHERE decided_at IS NOT NULL;
-- At most one live draft per change order.
CREATE UNIQUE INDEX versions_single_draft_idx
  ON change_order_versions (change_order_id)
  WHERE status = 'DRAFT';

CREATE TABLE line_items (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version_id uuid NOT NULL REFERENCES change_order_versions(id) ON DELETE RESTRICT,
  position integer NOT NULL CHECK (position >= 0),
  description text NOT NULL,
  quantity numeric(18,3) NOT NULL CHECK (quantity > 0),
  unit text,
  direction smallint NOT NULL CHECK (direction IN (-1, 1)),
  unit_price_minor bigint NOT NULL CHECK (unit_price_minor >= 0),
  tax_rate_bps integer NOT NULL DEFAULT 0 CHECK (tax_rate_bps BETWEEN 0 AND 10000),
  subtotal_minor bigint NOT NULL,
  tax_minor bigint NOT NULL,
  total_minor bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (version_id, position),
  CHECK (total_minor = subtotal_minor + tax_minor),
  -- The stored sign must agree with the declared direction.
  CHECK ((direction = 1 AND subtotal_minor >= 0) OR (direction = -1 AND subtotal_minor <= 0))
);

CREATE INDEX line_items_version_idx ON line_items (version_id, position);

CREATE TABLE version_attachments (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version_id uuid NOT NULL REFERENCES change_order_versions(id) ON DELETE CASCADE,
  file_object_id uuid NOT NULL REFERENCES file_objects(id) ON DELETE RESTRICT,
  position integer NOT NULL CHECK (position >= 0),
  caption text,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (version_id, file_object_id),
  UNIQUE (version_id, position)
);

-- ---------------------------------------------------------------------------
-- Approval tokens, public sessions, OTP, decisions
-- ---------------------------------------------------------------------------

CREATE TABLE approval_tokens (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version_id uuid NOT NULL REFERENCES change_order_versions(id) ON DELETE CASCADE,
  -- Only the hash is stored. The plaintext is returned exactly once (§3.4).
  token_hash bytea NOT NULL UNIQUE,
  approver_contact_id uuid NOT NULL REFERENCES contacts(id),
  assurance_required assurance_level NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  revoked_reason text
    CHECK (revoked_reason IS NULL OR revoked_reason IN
      ('DECIDED','SUPERSEDED','CANCELLED','EXPIRED','LEAKED','MANUAL')),
  view_count integer NOT NULL DEFAULT 0,
  first_viewed_at timestamptz,
  last_viewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- One live token per version; revoked ones stay for the audit trail.
CREATE UNIQUE INDEX approval_tokens_live_idx
  ON approval_tokens (version_id) WHERE revoked_at IS NULL;
CREATE INDEX approval_tokens_expiry_idx
  ON approval_tokens (expires_at) WHERE revoked_at IS NULL;

CREATE TABLE public_sessions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  approval_token_id uuid NOT NULL REFERENCES approval_tokens(id) ON DELETE CASCADE,
  version_id uuid NOT NULL REFERENCES change_order_versions(id) ON DELETE CASCADE,
  session_token_hash bytea NOT NULL UNIQUE,
  csrf_token_hash bytea NOT NULL,
  assurance_achieved assurance_level NOT NULL DEFAULT 'A0',
  verified_phone_e164 text,
  verified_at timestamptz,
  ip_hash bytea,
  user_agent text,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX public_sessions_token_idx ON public_sessions (approval_token_id);
CREATE INDEX public_sessions_expiry_idx ON public_sessions (expires_at);

CREATE TABLE otp_challenges (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  public_session_id uuid NOT NULL REFERENCES public_sessions(id) ON DELETE CASCADE,
  contact_id uuid NOT NULL REFERENCES contacts(id),
  destination_e164 text NOT NULL,
  -- Salted hash only; the code itself is never stored or logged (report §11.5).
  code_hash bytea NOT NULL,
  salt text NOT NULL,
  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  provider_message_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX otp_challenges_session_idx
  ON otp_challenges (public_session_id, created_at DESC);
CREATE INDEX otp_challenges_contact_idx
  ON otp_challenges (contact_id, created_at DESC);

CREATE TABLE decisions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  -- Report §7.8: "a unique partial index allows at most one terminal decision
  -- per version". A plain UNIQUE is stronger and simpler here: one decision row
  -- per version, full stop.
  version_id uuid NOT NULL UNIQUE REFERENCES change_order_versions(id) ON DELETE RESTRICT,
  type decision_type NOT NULL,
  signer_name text NOT NULL,
  signer_comment text,
  assurance_achieved assurance_level NOT NULL,
  verified_phone_e164 text,
  public_session_id uuid REFERENCES public_sessions(id),
  -- Keyed hash, not the raw address (report §12.3).
  ip_hash bytea,
  user_agent text,
  declaration_text text NOT NULL,
  terms_version text NOT NULL,
  occurred_at timestamptz NOT NULL,
  receipt_token_hash bytea UNIQUE,
  receipt_display_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX decisions_org_occurred_idx
  ON decisions (organization_id, occurred_at DESC);
CREATE INDEX decisions_project_idx ON decisions (project_id, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- Audit chain
-- ---------------------------------------------------------------------------

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  aggregate_type text NOT NULL,
  aggregate_id uuid NOT NULL,
  sequence bigint NOT NULL CHECK (sequence > 0),
  event_type text NOT NULL,
  actor_type actor_type NOT NULL,
  actor_id text,
  payload jsonb NOT NULL,
  occurred_at timestamptz NOT NULL,
  previous_hash bytea,
  event_hash bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (aggregate_type, aggregate_id, sequence)
);

CREATE INDEX audit_aggregate_idx
  ON audit_events (aggregate_type, aggregate_id, sequence);
CREATE INDEX audit_org_occurred_idx
  ON audit_events (organization_id, occurred_at DESC);
CREATE INDEX audit_project_idx
  ON audit_events (project_id, occurred_at DESC) WHERE project_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Numbering
-- ---------------------------------------------------------------------------

CREATE TABLE document_sequences (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  -- The all-zero UUID stands in for "organization scope" so the primary key
  -- stays simple and the UPSERT in report §8.2 works unchanged.
  project_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind IN ('CHANGE_ORDER','PROJECT','EVIDENCE_PACK')),
  next_value integer NOT NULL CHECK (next_value > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, project_id, kind)
);

-- ---------------------------------------------------------------------------
-- Outbox, jobs, webhook inbox, idempotency, rate limits
-- ---------------------------------------------------------------------------

CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  topic text NOT NULL,
  aggregate_id uuid NOT NULL,
  payload jsonb NOT NULL,
  available_at timestamptz NOT NULL DEFAULT now(),
  attempt_count integer NOT NULL DEFAULT 0,
  leased_until timestamptz,
  published_at timestamptz,
  last_error_code text,
  last_error_at timestamptz,
  dead_lettered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX outbox_unpublished_idx
  ON outbox_events (available_at, created_at)
  WHERE published_at IS NULL AND dead_lettered_at IS NULL;

CREATE TABLE job_queue (
  id uuid PRIMARY KEY,
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  kind text NOT NULL,
  -- Report §13.4: at-least-once delivery, so every handler is idempotent and a
  -- dedupe key collapses repeated enqueues of the same intent.
  dedupe_key text,
  payload jsonb NOT NULL,
  priority integer NOT NULL DEFAULT 50,
  status job_status NOT NULL DEFAULT 'PENDING',
  available_at timestamptz NOT NULL DEFAULT now(),
  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 6,
  leased_until timestamptz,
  leased_by text,
  last_error text,
  last_error_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX job_queue_dedupe_idx
  ON job_queue (dedupe_key)
  WHERE dedupe_key IS NOT NULL AND status IN ('PENDING','RUNNING');
CREATE INDEX job_queue_claim_idx
  ON job_queue (status, priority, available_at)
  WHERE status = 'PENDING';
CREATE INDEX job_queue_lease_idx
  ON job_queue (leased_until) WHERE status = 'RUNNING';

CREATE TABLE webhook_inbox (
  id uuid PRIMARY KEY,
  provider text NOT NULL,
  provider_account_id text,
  -- Report §9.5: dedupe by provider + account + event id.
  provider_event_id text NOT NULL,
  signature_verified boolean NOT NULL DEFAULT false,
  raw_payload jsonb NOT NULL,
  headers jsonb,
  provider_event_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  process_error text,
  UNIQUE (provider, provider_account_id, provider_event_id)
);

CREATE INDEX webhook_inbox_unprocessed_idx
  ON webhook_inbox (received_at) WHERE processed_at IS NULL;

CREATE TABLE idempotency_records (
  id uuid PRIMARY KEY,
  -- Report §7.6: unique on (scope, actor_or_token_id, key).
  scope text NOT NULL,
  subject_id text NOT NULL,
  idempotency_key text NOT NULL,
  request_hash bytea NOT NULL,
  status text NOT NULL DEFAULT 'IN_PROGRESS'
    CHECK (status IN ('IN_PROGRESS','COMPLETED','FAILED')),
  resource_id uuid,
  response_status integer,
  response_body jsonb,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (scope, subject_id, idempotency_key)
);

CREATE INDEX idempotency_expiry_idx ON idempotency_records (expires_at);

CREATE TABLE rate_limit_counters (
  bucket_key text NOT NULL,
  window_start timestamptz NOT NULL,
  count integer NOT NULL DEFAULT 0,
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (bucket_key, window_start)
);

CREATE INDEX rate_limit_expiry_idx ON rate_limit_counters (expires_at);

-- ---------------------------------------------------------------------------
-- Messaging
-- ---------------------------------------------------------------------------

CREATE TABLE messages (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version_id uuid REFERENCES change_order_versions(id) ON DELETE CASCADE,
  contact_id uuid REFERENCES contacts(id),
  channel text NOT NULL
    CHECK (channel IN ('WHATSAPP_NATIVE_SHARE','WHATSAPP_CLOUD_API','EMAIL','SMS','COPY_LINK')),
  purpose text NOT NULL
    CHECK (purpose IN ('REQUEST','REMINDER','DECISION_RECEIPT','OTP')),
  -- Native share can only ever reach SHARE_INTENT_OPENED: the system does not
  -- observe delivery and must not claim it (report §10.3).
  status text NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING','SHARE_INTENT_OPENED','ACCEPTED','SENT',
                      'DELIVERED','READ','FAILED','SUPPRESSED')),
  suppression_reason text,
  provider text,
  provider_message_id text,
  dedupe_key text,
  error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX messages_org_created_idx ON messages (organization_id, created_at DESC);
CREATE INDEX messages_version_idx ON messages (version_id, created_at DESC);
CREATE UNIQUE INDEX messages_dedupe_idx ON messages (dedupe_key)
  WHERE dedupe_key IS NOT NULL;
CREATE INDEX messages_provider_idx ON messages (provider, provider_message_id)
  WHERE provider_message_id IS NOT NULL;

CREATE TABLE message_events (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  status text NOT NULL,
  provider_event_at timestamptz,
  received_at timestamptz NOT NULL DEFAULT now(),
  payload jsonb
);

CREATE INDEX message_events_message_idx ON message_events (message_id, received_at DESC);

-- ---------------------------------------------------------------------------
-- Documents and exports
-- ---------------------------------------------------------------------------

CREATE TABLE generated_documents (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  version_id uuid REFERENCES change_order_versions(id) ON DELETE CASCADE,
  kind text NOT NULL
    CHECK (kind IN ('EVIDENCE_PDF','PROJECT_EVIDENCE_PACK','ACCOUNTING_CSV','ORGANIZATION_EXPORT')),
  status text NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING','GENERATING','READY','FAILED')),
  storage_key text,
  file_sha256 bytea,
  byte_size bigint,
  -- Report §8.5: template, renderer, object version and time are all recorded.
  template_version text NOT NULL,
  renderer_version text,
  generator_version text,
  storage_object_version text,
  manifest jsonb,
  manifest_sha256 bytea,
  error text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  generated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX generated_documents_version_idx
  ON generated_documents (version_id, requested_at DESC);
CREATE INDEX generated_documents_org_idx
  ON generated_documents (organization_id, kind, requested_at DESC);
-- One live evidence PDF per version; regeneration supersedes by requested_at.
CREATE INDEX generated_documents_ready_idx
  ON generated_documents (version_id, kind) WHERE status = 'READY';

-- ---------------------------------------------------------------------------
-- Billing
-- ---------------------------------------------------------------------------

CREATE TABLE subscriptions (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
  plan_code text NOT NULL
    CHECK (plan_code IN ('TRIAL','STARTER_MONTHLY','PROJECT_PASS','PRO_MONTHLY')),
  status text NOT NULL
    CHECK (status IN ('TRIALING','ACTIVE','GRACE','LAPSED','CANCELLED')),
  current_period_start timestamptz NOT NULL,
  current_period_end timestamptz NOT NULL,
  grace_ends_at timestamptz,
  provider text,
  provider_subscription_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (current_period_end > current_period_start)
);

CREATE TABLE entitlement_counters (
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  period_start timestamptz NOT NULL,
  completed_decisions integer NOT NULL DEFAULT 0,
  sends integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, period_start)
);

CREATE TABLE payment_intents (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE SET NULL,
  version_id uuid REFERENCES change_order_versions(id) ON DELETE SET NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor > 0),
  currency char(3) NOT NULL,
  status text NOT NULL DEFAULT 'CREATED'
    CHECK (status IN ('CREATED','PENDING','PAID','FAILED','CANCELLED','REFUNDED')),
  provider text,
  provider_order_id text,
  provider_payment_id text,
  checkout_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_order_id)
);

-- ---------------------------------------------------------------------------
-- Governance: support access, data-subject requests, repairs, legal hold
-- ---------------------------------------------------------------------------

CREATE TABLE support_access_grants (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  granted_to_user_id uuid NOT NULL REFERENCES users(id),
  granted_by_user_id uuid NOT NULL REFERENCES users(id),
  reason text NOT NULL,
  scope text NOT NULL DEFAULT 'METADATA'
    CHECK (scope IN ('METADATA','DOCUMENTS')),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > created_at)
);

CREATE INDEX support_grants_active_idx
  ON support_access_grants (granted_to_user_id, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE data_subject_requests (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  subject_type text NOT NULL CHECK (subject_type IN ('CUSTOMER','CONTACT','USER')),
  subject_id uuid,
  request_type text NOT NULL
    CHECK (request_type IN ('ACCESS','CORRECTION','EXPORT','ERASURE')),
  status text NOT NULL DEFAULT 'RECEIVED'
    CHECK (status IN ('RECEIVED','IN_REVIEW','FULFILLED','REFUSED','PARTIAL')),
  -- Report §9.8: erasure is reconciled against contractual evidence needs.
  resolution_note text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolved_by_user_id uuid REFERENCES users(id)
);

CREATE TABLE legal_holds (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  project_id uuid REFERENCES projects(id) ON DELETE CASCADE,
  reason text NOT NULL,
  placed_by_user_id uuid REFERENCES users(id),
  placed_at timestamptz NOT NULL DEFAULT now(),
  released_at timestamptz,
  released_by_user_id uuid REFERENCES users(id)
);

CREATE INDEX legal_holds_active_idx ON legal_holds (project_id)
  WHERE released_at IS NULL;

-- Report §9.6: repairs are recorded with before/after digests, never silent.
CREATE TABLE repair_events (
  id uuid PRIMARY KEY,
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  target_table text NOT NULL,
  target_id uuid,
  command text NOT NULL,
  reason text NOT NULL,
  before_digest bytea,
  after_digest bytea,
  before_value jsonb,
  after_value jsonb,
  performed_by text NOT NULL,
  approved_by text,
  performed_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Reminder schedule
-- ---------------------------------------------------------------------------

CREATE TABLE reminder_schedules (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  version_id uuid NOT NULL REFERENCES change_order_versions(id) ON DELETE CASCADE,
  policy_step integer NOT NULL,
  channel text NOT NULL,
  dedupe_key text NOT NULL UNIQUE,
  due_at timestamptz NOT NULL,
  sent_at timestamptz,
  suppressed_reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX reminder_due_idx ON reminder_schedules (due_at)
  WHERE sent_at IS NULL AND suppressed_reason IS NULL;
